[package]
name = "relmchef"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19.0"
relm4 = { version = "0.8.1", features = ["libadwaita", "gnome_46"] }
serde = { version = "1.0.197", features = ["derive"] }
